#!/usr/bin/env node
/**
 * Squad Scaffold - Creates directory structure for new squads.
 *
 * Usage:
 *   node scaffold-squad.cjs <slug> [--name "Display Name"]
 *   node scaffold-squad.cjs  # Uses .active-squad
 *
 * Creates:
 *   squads/{slug}/
 *   ├── agents/
 *   ├── tasks/
 *   ├── templates/
 *   ├── data/
 *   ├── checklists/
 *   ├── docs/
 *   ├── scripts/
 *   ├── config.yaml
 *   └── README.md
 */

const fs = require('fs');
const path = require('path');

// ═══════════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════

const SQUADS_BASE = path.resolve(__dirname, '..', '..'); // squads/
const ACTIVE_SQUAD_PATH = path.join(SQUADS_BASE, '.active-squad');

const DIRECTORIES = [
  'agents',
  'tasks',
  'templates',
  'data',
  'checklists',
  'docs',
  'scripts'
];

// ═══════════════════════════════════════════════════════════════════════════
// TEMPLATES
// ═══════════════════════════════════════════════════════════════════════════

function getReadmeTemplate(slug, displayName, date) {
  return `# ${displayName} Squad

**Status:** 🚧 In Development
**Created:** ${date}

---

## Overview

*Description pending - update after research phase*

---

## Agents

| Agent | Role | Status |
|-------|------|--------|
| TBD | TBD | 📋 Planned |

---

## Quick Start

\`\`\`bash
# Check squad state
node squads/squad-creator-pro/scripts/squad-state-manager.cjs get ${slug}

# Load context for an agent
node squads/squad-creator-pro/scripts/squad-context-loader.cjs oalanicolas ${slug}
\`\`\`

---

## Structure

| Directory | Purpose |
|-----------|---------|
| \`agents/\` | Agent definitions |
| \`tasks/\` | Task workflows |
| \`templates/\` | Reusable templates |
| \`data/\` | Knowledge base, frameworks |
| \`checklists/\` | Validation checklists |
| \`docs/\` | Squad documentation |
| \`scripts/\` | Utility scripts |

---

## Pipeline Progress

Check current state:

\`\`\`bash
node squads/squad-creator-pro/scripts/squad-state-manager.cjs get ${slug}
\`\`\`

---

*Generated by squad-creator pipeline*
`;
}

function getConfigTemplate(slug, displayName, date) {
  return `# ${displayName} Squad Configuration
# Generated: ${date}

squad:
  slug: ${slug}
  display_name: "${displayName}"
  created_at: "${date}"
  status: in_development

metadata:
  source_mind: null
  target_domain: null
  description: null

# Agent definitions (populated during scaffolding phase)
agents: []

# Task definitions (populated during task anatomy phase)
tasks: []

# Quality gates
quality:
  checkpoint_required: true
  checkpoint_phase: quality_gate

# Pipeline configuration
pipeline:
  workflow: create-squad
  current_phase: init
`;
}

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

function outputJson(data) {
  console.log(JSON.stringify(data));
}

function outputError(code, message, details = {}) {
  outputJson({ success: false, error: { code, message, details } });
}

function resolveSlug(cliSlug) {
  if (cliSlug && !cliSlug.startsWith('-')) return cliSlug;
  if (fs.existsSync(ACTIVE_SQUAD_PATH)) {
    return fs.readFileSync(ACTIVE_SQUAD_PATH, 'utf8').trim();
  }
  return null;
}

function getStatePath(slug) {
  return path.join(SQUADS_BASE, slug, 'metadata', 'state.json');
}

function readState(slug) {
  const statePath = getStatePath(slug);
  if (fs.existsSync(statePath)) {
    try {
      return JSON.parse(fs.readFileSync(statePath, 'utf8'));
    } catch {
      return null;
    }
  }
  return null;
}

function parseArg(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1 || idx + 1 >= args.length) return null;
  return args[idx + 1];
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════

function main() {
  const args = process.argv.slice(2);

  if (args[0] === '--help' || args[0] === '-h') {
    console.log(`Squad Scaffold - Creates directory structure for new squads

Usage:
  node scaffold-squad.cjs <slug> [--name "Display Name"]
  node scaffold-squad.cjs  # Uses .active-squad

Options:
  --name "Name"    Display name for the squad (default: slug title-cased)

Creates directories: ${DIRECTORIES.join(', ')}
Creates files: README.md, config.yaml`);
    process.exit(0);
  }

  // Resolve slug
  const cliSlug = args[0];
  const slug = resolveSlug(cliSlug);

  if (!slug) {
    outputError('NO_SLUG', 'No slug provided and no .active-squad file found', {
      hint: 'Run: node squad-state-manager.cjs init <slug> first'
    });
    process.exit(1);
  }

  // Validate slug format
  if (!/^[a-z0-9]+(_[a-z0-9]+)*$/.test(slug)) {
    outputError('INVALID_SLUG', 'Slug must be snake_case', {
      received: slug,
      expected_pattern: '^[a-z0-9]+(_[a-z0-9]+)*$'
    });
    process.exit(1);
  }

  // Get display name from args or state or derive from slug
  const state = readState(slug);
  const argName = parseArg(args, '--name');
  const displayName = argName ||
    (state && state.display_name) ||
    slug.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  const date = new Date().toISOString().split('T')[0];
  const squadDir = path.join(SQUADS_BASE, slug);
  const created = [];
  const skipped = [];

  // Create directories
  for (const dir of DIRECTORIES) {
    const dirPath = path.join(squadDir, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      // Create .gitkeep
      fs.writeFileSync(path.join(dirPath, '.gitkeep'), '');
      created.push(`${dir}/`);
    } else {
      skipped.push(`${dir}/`);
    }
  }

  // Create README.md
  const readmePath = path.join(squadDir, 'README.md');
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, getReadmeTemplate(slug, displayName, date));
    created.push('README.md');
  } else {
    skipped.push('README.md');
  }

  // Create config.yaml
  const configPath = path.join(squadDir, 'config.yaml');
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, getConfigTemplate(slug, displayName, date));
    created.push('config.yaml');
  } else {
    skipped.push('config.yaml');
  }

  outputJson({
    success: true,
    slug,
    display_name: displayName,
    path: squadDir,
    created,
    skipped,
    message: created.length > 0
      ? `Created ${created.length} items`
      : 'Structure already exists'
  });
}

main();
